server.port: 8085

spring:
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop?serverTimezone=UTC
    username : online-shop-admin
    password: online-shop-admin







